/**
 * Browser-compatible deterministic credential generator for seed/demo accounts.
 * Mirrors the backend's seedCredentials.js logic using a simple hash approach
 * that works without Node.js crypto module.
 *
 * Used ONLY for the quick-login demo buttons on the login page.
 */

/**
 * Simple deterministic hash function (djb2 variant) for browser use.
 * Not cryptographic — only used for demo credential generation.
 */
function simpleHash(str) {
  let h1 = 0xdeadbeef;
  let h2 = 0x41c6ce57;
  for (let i = 0; i < str.length; i++) {
    const ch = str.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507);
  h1 ^= Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507);
  h2 ^= Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return (4294967296 * (2097151 & h2) + (h1 >>> 0)).toString(16).padStart(16, '0');
}

/**
 * Generate a deterministic credential for a given account key.
 * Must produce the SAME output as the backend seedCredentials.js.
 *
 * Since we need exact parity with the Node.js HMAC-SHA256 implementation,
 * we use a pre-computed lookup for the demo accounts.
 */

// Pre-computed map: these are generated by the backend's seedCredentials utility
// at build time. They are NOT secrets — they are demo-only credentials visible
// on the login page for quick-access convenience.
const SEED_CREDENTIAL_MAP = {};

/**
 * Initialize the credential map by computing values that match the backend.
 * The backend uses HMAC-SHA256 with domain 'republic-finance-los-seed-v1',
 * so we replicate the exact algorithm here using SubtleCrypto when available,
 * or fall back to a synchronous implementation.
 */

// Synchronous fallback: We embed the exact algorithm from the backend
// using a pure-JS SHA-256 + HMAC implementation for deterministic output.
function generateSeedCredential(accountKey) {
  // If we have a cached value, return it
  if (SEED_CREDENTIAL_MAP[accountKey]) return SEED_CREDENTIAL_MAP[accountKey];

  // Use the same algorithm as the backend: HMAC-SHA256 with fixed domain
  // Since we can't use Node crypto in browser, we use a JS implementation
  const hash = hmacSha256Hex('republic-finance-los-seed-v1', accountKey);

  const upper = String.fromCharCode(65 + (parseInt(hash.slice(0, 2), 16) % 26));
  const lower = String.fromCharCode(97 + (parseInt(hash.slice(2, 4), 16) % 26));
  const digit = String(parseInt(hash.slice(4, 6), 16) % 10);
  const specials = '!@#$%&*';
  const special = specials[parseInt(hash.slice(6, 8), 16) % specials.length];

  const body = hash.slice(8, 16).split('').map((ch, i) => {
    return i % 2 === 0 ? ch.toUpperCase() : ch;
  }).join('');

  const credential = `${upper}${lower}${digit}${special}${body}`;
  SEED_CREDENTIAL_MAP[accountKey] = credential;
  return credential;
}

// ── Pure-JS SHA-256 + HMAC (for browser parity with Node crypto) ──────────

function sha256(message) {
  const K = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
  ];

  function rotr(n, x) { return (x >>> n) | (x << (32 - n)); }
  function ch(x, y, z) { return (x & y) ^ (~x & z); }
  function maj(x, y, z) { return (x & y) ^ (x & z) ^ (y & z); }
  function sigma0(x) { return rotr(2, x) ^ rotr(13, x) ^ rotr(22, x); }
  function sigma1(x) { return rotr(6, x) ^ rotr(11, x) ^ rotr(25, x); }
  function gamma0(x) { return rotr(7, x) ^ rotr(18, x) ^ (x >>> 3); }
  function gamma1(x) { return rotr(17, x) ^ rotr(19, x) ^ (x >>> 10); }

  // Convert string to byte array
  const msgBytes = typeof message === 'string'
    ? Array.from(new TextEncoder().encode(message))
    : Array.from(message);

  // Pre-processing: adding padding bits
  const msgLen = msgBytes.length;
  msgBytes.push(0x80);
  while ((msgBytes.length % 64) !== 56) msgBytes.push(0x00);

  // Append original length in bits as 64-bit big-endian
  const bitLen = msgLen * 8;
  for (let i = 56; i >= 0; i -= 8) {
    msgBytes.push((bitLen / Math.pow(2, i)) & 0xff);
  }

  let H = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];

  for (let offset = 0; offset < msgBytes.length; offset += 64) {
    const W = new Array(64);
    for (let t = 0; t < 16; t++) {
      W[t] = (msgBytes[offset + t * 4] << 24) | (msgBytes[offset + t * 4 + 1] << 16) |
             (msgBytes[offset + t * 4 + 2] << 8) | msgBytes[offset + t * 4 + 3];
    }
    for (let t = 16; t < 64; t++) {
      W[t] = (gamma1(W[t - 2]) + W[t - 7] + gamma0(W[t - 15]) + W[t - 16]) | 0;
    }

    let [a, b, c, d, e, f, g, h] = H;

    for (let t = 0; t < 64; t++) {
      const T1 = (h + sigma1(e) + ch(e, f, g) + K[t] + W[t]) | 0;
      const T2 = (sigma0(a) + maj(a, b, c)) | 0;
      h = g; g = f; f = e; e = (d + T1) | 0;
      d = c; c = b; b = a; a = (T1 + T2) | 0;
    }

    H = [
      (H[0] + a) | 0, (H[1] + b) | 0, (H[2] + c) | 0, (H[3] + d) | 0,
      (H[4] + e) | 0, (H[5] + f) | 0, (H[6] + g) | 0, (H[7] + h) | 0,
    ];
  }

  return new Uint8Array(H.flatMap(h => [(h >> 24) & 0xff, (h >> 16) & 0xff, (h >> 8) & 0xff, h & 0xff]));
}

function hmacSha256Hex(key, message) {
  const blockSize = 64;
  let keyBytes = typeof key === 'string' ? Array.from(new TextEncoder().encode(key)) : Array.from(key);

  if (keyBytes.length > blockSize) {
    keyBytes = Array.from(sha256(keyBytes));
  }
  while (keyBytes.length < blockSize) keyBytes.push(0x00);

  const ipad = keyBytes.map(b => b ^ 0x36);
  const opad = keyBytes.map(b => b ^ 0x5c);

  const msgBytes = typeof message === 'string' ? Array.from(new TextEncoder().encode(message)) : Array.from(message);

  const innerHash = sha256(new Uint8Array([...ipad, ...msgBytes]));
  const outerHash = sha256(new Uint8Array([...opad, ...innerHash]));

  return Array.from(outerHash).map(b => b.toString(16).padStart(2, '0')).join('');
}

export { generateSeedCredential };
